name = "taxis"
version = "0.1.0"
defaultTargets = ["taxis"]
testDriver = "test"

[[require]]
name = "leansqlite"
git = "https://github.com/leanprover/leansqlite"
rev = "v4.31.0"

[[lean_lib]]
name = "Taxis"

[[lean_exe]]
name = "taxis"
root = "Main"

[[lean_exe]]
name = "test"
root = "Tests"
