import Db

/-!
# The initial schema

Generated with `Db.Migration.render "0001_initial" (planSteps [] Taxis.Db.Schema.schema)` from the
declaration in `Taxis.Db.Schema` as it stood at the commit that added this file: the 18 tables in
dependency order, each with its columns, defaults, primary key, `UNIQUE` groups and foreign keys,
followed by the 23 indexes.

From here on it is the **record** of that schema rather than a description of it. The declaration
may move on; this file must not follow, because a database that has applied this migration will
never apply it again, and a step edited after the fact is a step that ran in one deployment and
not in another. A change to the schema is a new migration — see `Taxis.Db.Migrations`. The only
edit this file may take is a fix to a bug no database has applied yet, which in practice means
before the change that introduced it is released.

(`makemigrations` writes "edit freely" above everything it generates, and that is left as it came:
it is true of a migration that is still being written, and stops being true the moment one ships.)
-/

/-- Generated by `makemigrations`; edit freely. -/
def migration_0001_initial : Db.Migration.Migration where
  name := "0001_initial"
  steps := [
    .createTable "labels"
      { columns := .ofList
          [("name", { type := .text, nullable := false }),
           ("description", { type := .text, nullable := true }),
           ("color", { type := .text, nullable := false, default? := some (.str "#6b7280") }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"],
        unique := [["name"]] },
    .createTable "groups"
      { columns := .ofList
          [("name", { type := .text, nullable := false }),
           ("description", { type := .text, nullable := true }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"],
        unique := [["name"]] },
    .createTable "actors"
      { columns := .ofList
          [("admin", { type := .bool, nullable := false, default? := some (.bool false) }),
           ("bot", { type := .bool, nullable := false, default? := some (.bool false) }),
           ("email", { type := .text, nullable := false }),
           ("github_id", { type := .text, nullable := true }),
           ("google_sub", { type := .text, nullable := true }),
           ("display_name", { type := .text, nullable := false }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"],
        unique := [["email"], ["google_sub"], ["github_id"]] },
    .createTable "sessions"
      { columns := .ofList
          [("created_at", { type := .int, nullable := false, default? := some (.call "unixepoch()") }),
           ("expires_at", { type := .int, nullable := false }),
           ("actor_id", { type := .int, nullable := false }),
           ("id", { type := .text, nullable := false })],
        primaryKey := ["id"],
        foreignKeys :=
          [{ columns := ["actor_id"], foreignTable := "actors", foreignColumns := ["id"], onDelete := .cascade }] },
    .createTable "api_tokens"
      { columns := .ofList
          [("name", { type := .text, nullable := false, default? := some (.str "") }),
           ("token_hash", { type := .text, nullable := false }),
           ("created_at", { type := .int, nullable := false, default? := some (.call "unixepoch()") }),
           ("actor_id", { type := .int, nullable := false }),
           ("prefix", { type := .text, nullable := false, default? := some (.str "") }),
           ("last_used", { type := .int, nullable := true }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"],
        unique := [["token_hash"]],
        foreignKeys :=
          [{ columns := ["actor_id"], foreignTable := "actors", foreignColumns := ["id"], onDelete := .cascade }] },
    .createTable "actor_groups"
      { columns := .ofList
          [("actor_id", { type := .int, nullable := false }),
           ("group_id", { type := .int, nullable := false })],
        primaryKey := ["actor_id", "group_id"],
        foreignKeys :=
          [{ columns := ["actor_id"], foreignTable := "actors", foreignColumns := ["id"], onDelete := .cascade },
           { columns := ["group_id"], foreignTable := "groups", foreignColumns := ["id"], onDelete := .cascade }] },
    .createTable "issues"
      { columns := .ofList
          [("created_at", { type := .int, nullable := false, default? := some (.call "unixepoch()") }),
           ("title", { type := .text, nullable := false }),
           ("deadline", { type := .int, nullable := true }),
           ("updated_at", { type := .int, nullable := false, default? := some (.call "unixepoch()") }),
           ("locked", { type := .bool, nullable := false, default? := some (.bool false) }),
           ("goal", { type := .text, nullable := false, default? := some (.str "") }),
           ("description", { type := .text, nullable := false, default? := some (.str "") }),
           ("creator_id", { type := .int, nullable := true }),
           ("state", { type := .text, nullable := false, default? := some (.str "open") }),
           ("parent_id", { type := .int, nullable := true }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"],
        foreignKeys :=
          [{ columns := ["parent_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .setNull },
           { columns := ["creator_id"], foreignTable := "actors", foreignColumns := ["id"], onDelete := .setNull }] },
    .createTable "artifacts"
      { columns := .ofList
          [("kind", { type := .text, nullable := false }),
           ("issue_id", { type := .int, nullable := false }),
           ("payload", { type := .text, nullable := false, default? := some (.str "null") }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"],
        foreignKeys :=
          [{ columns := ["issue_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade }] },
    .createTable "issue_visibility"
      { columns := .ofList
          [("issue_id", { type := .int, nullable := false }),
           ("group_id", { type := .int, nullable := false })],
        primaryKey := ["issue_id", "group_id"],
        foreignKeys :=
          [{ columns := ["issue_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade },
           { columns := ["group_id"], foreignTable := "groups", foreignColumns := ["id"], onDelete := .cascade }] },
    .createTable "review_requests"
      { columns := .ofList
          [("created_at", { type := .int, nullable := false, default? := some (.call "unixepoch()") }),
           ("requested_by", { type := .int, nullable := true }),
           ("actor_id", { type := .int, nullable := false }),
           ("issue_id", { type := .int, nullable := false }),
           ("resolved_at", { type := .int, nullable := true }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"],
        foreignKeys :=
          [{ columns := ["issue_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade },
           { columns := ["actor_id"], foreignTable := "actors", foreignColumns := ["id"], onDelete := .cascade },
           { columns := ["requested_by"], foreignTable := "actors", foreignColumns := ["id"], onDelete := .setNull }] },
    .createTable "issue_labels"
      { columns := .ofList
          [("label_id", { type := .int, nullable := false }),
           ("issue_id", { type := .int, nullable := false })],
        primaryKey := ["issue_id", "label_id"],
        foreignKeys :=
          [{ columns := ["issue_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade },
           { columns := ["label_id"], foreignTable := "labels", foreignColumns := ["id"], onDelete := .cascade }] },
    .createTable "checks"
      { columns := .ofList
          [("last_run", { type := .int, nullable := true }),
           ("kind", { type := .text, nullable := false }),
           ("detail", { type := .text, nullable := true }),
           ("config", { type := .text, nullable := false, default? := some (.str "null") }),
           ("status", { type := .text, nullable := false, default? := some (.str "pending") }),
           ("issue_id", { type := .int, nullable := false }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"],
        foreignKeys :=
          [{ columns := ["issue_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade }] },
    .createTable "issue_participants"
      { columns := .ofList
          [("actor_id", { type := .int, nullable := false }),
           ("issue_id", { type := .int, nullable := false })],
        primaryKey := ["issue_id", "actor_id"],
        foreignKeys :=
          [{ columns := ["issue_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade },
           { columns := ["actor_id"], foreignTable := "actors", foreignColumns := ["id"], onDelete := .cascade }] },
    .createTable "issue_dependencies"
      { columns := .ofList
          [("depends_on_id", { type := .int, nullable := false }),
           ("issue_id", { type := .int, nullable := false })],
        primaryKey := ["issue_id", "depends_on_id"],
        foreignKeys :=
          [{ columns := ["issue_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade },
           { columns := ["depends_on_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade }] },
    .createTable "events"
      { columns := .ofList
          [("created_at", { type := .int, nullable := false, default? := some (.call "unixepoch()") }),
           ("kind", { type := .text, nullable := false }),
           ("actor_id", { type := .int, nullable := true }),
           ("issue_id", { type := .int, nullable := false }),
           ("data", { type := .text, nullable := false, default? := some (.str "{}") }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"],
        foreignKeys :=
          [{ columns := ["issue_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade },
           { columns := ["actor_id"], foreignTable := "actors", foreignColumns := ["id"], onDelete := .setNull }] },
    .createTable "notifications"
      { columns := .ofList
          [("read", { type := .bool, nullable := false, default? := some (.bool false) }),
           ("created_at", { type := .int, nullable := false, default? := some (.call "unixepoch()") }),
           ("done", { type := .bool, nullable := false, default? := some (.bool false) }),
           ("kind", { type := .text, nullable := false }),
           ("actor_id", { type := .int, nullable := false }),
           ("issue_id", { type := .int, nullable := false }),
           ("data", { type := .text, nullable := false, default? := some (.str "{}") }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"],
        foreignKeys :=
          [{ columns := ["actor_id"], foreignTable := "actors", foreignColumns := ["id"], onDelete := .cascade },
           { columns := ["issue_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade }] },
    .createTable "comments"
      { columns := .ofList
          [("review", { type := .text, nullable := true }),
           ("created_at", { type := .int, nullable := false, default? := some (.call "unixepoch()") }),
           ("author_id", { type := .int, nullable := true }),
           ("updated_at", { type := .int, nullable := false, default? := some (.call "unixepoch()") }),
           ("body", { type := .text, nullable := false }),
           ("issue_id", { type := .int, nullable := false }),
           ("id", { type := .int, nullable := false, autoIncrement := true })],
        primaryKey := ["id"],
        foreignKeys :=
          [{ columns := ["issue_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade },
           { columns := ["author_id"], foreignTable := "actors", foreignColumns := ["id"], onDelete := .setNull }] },
    .createTable "issue_assignees"
      { columns := .ofList
          [("actor_id", { type := .int, nullable := false }),
           ("issue_id", { type := .int, nullable := false })],
        primaryKey := ["issue_id", "actor_id"],
        foreignKeys :=
          [{ columns := ["issue_id"], foreignTable := "issues", foreignColumns := ["id"], onDelete := .cascade },
           { columns := ["actor_id"], foreignTable := "actors", foreignColumns := ["id"], onDelete := .cascade }] },
    .createIndex "actor_groups" { name := "idx_actor_groups_group", keys := [{ column := "group_id" }] },
    .createIndex "api_tokens" { name := "idx_api_tokens_actor", keys := [{ column := "actor_id" }] },
    .createIndex "artifacts" { name := "idx_artifacts_issue", keys := [{ column := "issue_id" }] },
    .createIndex "checks" { name := "idx_checks_issue", keys := [{ column := "issue_id" }] },
    .createIndex "comments" { name := "idx_comments_issue", keys := [{ column := "issue_id" }] },
    .createIndex "comments" { name := "idx_comments_author", keys := [{ column := "author_id" }] },
    .createIndex "events" { name := "idx_events_issue", keys := [{ column := "issue_id" }] },
    .createIndex "events" { name := "idx_events_author", keys := [{ column := "actor_id" }] },
    .createIndex "issue_assignees" { name := "idx_issue_assignees_actor", keys := [{ column := "actor_id" }] },
    .createIndex "issue_dependencies" { name := "idx_issue_dependencies_dep", keys := [{ column := "depends_on_id" }] },
    .createIndex "issue_labels" { name := "idx_issue_labels_label", keys := [{ column := "label_id" }] },
    .createIndex "issue_participants" { name := "idx_issue_participants_actor", keys := [{ column := "actor_id" }] },
    .createIndex "issue_visibility" { name := "idx_issue_visibility_group", keys := [{ column := "group_id" }] },
    .createIndex "issues" { name := "idx_issues_state", keys := [{ column := "state" }] },
    .createIndex "issues" { name := "idx_issues_parent", keys := [{ column := "parent_id" }] },
    .createIndex "issues" { name := "idx_issues_updated", keys := [{ column := "updated_at", direction := .desc }, { column := "id", direction := .desc }] },
    .createIndex "issues" { name := "idx_issues_title", keys := [{ column := "title", collation := .caseInsensitive }, { column := "id" }] },
    .createIndex "issues" { name := "idx_issues_deadline", keys := [{ column := "deadline" }, { column := "id" }] },
    .createIndex "notifications" { name := "idx_notifications_actor", keys := [{ column := "actor_id" }, { column := "read" }] },
    .createIndex "notifications" { name := "idx_notifications_issue", keys := [{ column := "issue_id" }] },
    .createIndex "review_requests" { name := "idx_review_requests_issue", keys := [{ column := "issue_id" }] },
    .createIndex "review_requests" { name := "idx_review_requests_actor", keys := [{ column := "actor_id" }] },
    .createIndex "sessions" { name := "idx_sessions_actor", keys := [{ column := "actor_id" }] }
  ]
